### ISSUE TITLE
Crash when trying to show notifications under API 23

### ISSUE THREAD

**Issue by tuur29** [tuur29/fuzzyclock#58]
```
12-26 11:50:49.488 net.tuurlievens.fuzzyclockscreensaver E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: android.graphics.drawable.Icon
        at net.tuurlievens.fuzzyclockscreensaver.NotificationData.<init>(NotificationData.kt:12)
        at net.tuurlievens.fuzzyclockscreensaver.NotificationListener.onNotificationPosted(NotificationListener.kt:33)
        at net.tuurlievens.fuzzyclockscreensaver.NotificationListener$NLServiceReceiver.onReceive(NotificationListener.kt:59)
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:763)
        at android.os.Handler.handleCallback(Handler.java:730)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5103)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)

```

Same error as this: https://stackoverflow.com/questions/45582430/java-lang-noclassdeffounderror-android-graphics-drawable-icon but it should have been fixed in the v27 support library.

**Comment by tuur29** [comment]
Fixed by dc6e02c77bd923f02bea8319defa4b781c1060a8
